forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apache'
mod 'puppetlabs/mysql'
mod 'thias/php'
mod 'willdurand/composer'
mod 'drush', :git => 'git://git.drupal.org/project/puppet-drush.git'
